### ISSUE TITLE
Use phantomjs-prebuilt?

### ISSUE THREAD

**Issue by phildotdev** [mmacartney10/ghastlyjs#10]
I've found that using phantomjs-prebuilt is more reliable then just using phantom

https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by mmacartney10** [comment]
I will have a look at that, what makes it more reliable?

**Comment by furzeface** [comment]
👊🏾

**Comment by mmacartney10** [comment]
Phantomjs is dead in the water, all about chromy 💃

**Comment by furzeface** [comment]
ಠ_ಠ

**Comment by furzeface** [comment]
LGTM 👍
